# Generated by Django 5.1 on 2024-10-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcc_number', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('pesel', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabThumor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumor_number', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor1_segment1', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor1_segment2', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor1_segment3', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor1_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor2_segment1', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor2_segment2', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor2_segment3', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor2_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor3_segment1', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor3_segment2', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor3_segment3', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor3_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor4_segment1', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor4_segment2', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor4_segment3', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor4_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor5_segment1', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor5_segment2', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor5_segment3', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor5_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor6_segment1', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor6_segment2', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor6_segment3', models.CharField(blank=True, max_length=5, null=True)),
                ('thumor6_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('top_diameter', models.CharField(blank=True, max_length=5, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_date', models.DateField(blank=True, max_length=20, null=True)),
                ('albuminy', models.CharField(blank=True, max_length=20, null=True)),
                ('inr', models.CharField(blank=True, max_length=5, null=True)),
                ('kreatynina', models.CharField(blank=True, max_length=5, null=True)),
                ('sod_surowica', models.CharField(blank=True, max_length=5, null=True)),
                ('bilirubina_cal', models.CharField(blank=True, max_length=5, null=True)),
                ('li_rads_hcc', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('afp', models.CharField(blank=True, max_length=5, null=True)),
                ('plt', models.CharField(blank=True, max_length=5, null=True)),
                ('cea', models.CharField(blank=True, max_length=5, null=True)),
                ('ca19_9', models.CharField(blank=True, max_length=5, null=True)),
                ('cukrzyca', models.CharField(blank=True, choices=[('1', 'tak'), ('0', 'nie')], max_length=20, null=True)),
                ('marskosc', models.CharField(blank=True, choices=[('1', 'tak'), ('0', 'nie')], max_length=20, null=True)),
                ('wodobrzusze', models.CharField(blank=True, choices=[('1', '1/2 stopień'), ('2', '3/4 stopień')], max_length=20, null=True)),
                ('encefalopatia', models.CharField(blank=True, choices=[('1', '1/2 stopień'), ('2', '3/4 stopień')], max_length=20, null=True)),
                ('hbv', models.CharField(blank=True, choices=[('0', 'ujemne'), ('1', 'wyleczone'), ('2', 'dodatnie')], max_length=20, null=True)),
                ('hcv', models.CharField(blank=True, choices=[('0', 'ujemne'), ('1', 'wyleczone'), ('2', 'dodatnie')], max_length=20, null=True)),
                ('kommentarz', models.TextField(blank=True, max_length=300, null=True)),
                ('leczenie', models.TextField(blank=True, max_length=300, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('grupa_krwi', models.CharField(blank=True, choices=[('A', 'A'), ('A+', 'A+'), ('A-', 'A-'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('AB', 'AB'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O', 'O'), ('O+', 'O+'), ('O-', 'O-')], max_length=20, null=True)),
                ('patient_height', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Męska'), ('K', 'Żeńska')], max_length=5, null=True)),
                ('ecog', models.CharField(blank=True, max_length=5, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
